### ISSUE TITLE
Presubmit check should validate mapping annotations keys

### ISSUE THREAD

**Issue by yolocs** [abcxyz/pmap#72]
https://github.com/abcxyz/pmap/blob/main/pkg/mapping/processors/assetinventory.go#L162-L182

We use these keys (from CAIS) in the annotations. If somebody manually provides an annotation that has the same key, it could get overwritten by the CAIS processor.
We need to validate that the mapping is not using such well-known annotation keys.
Even better, CAIS info probably should be fully under a dedicated annotation. E.g.

```
annotations:
  assetInfo:
    iamPolicies:
    labels: foo
```

cc: @capri-xiyue
